-- Create the banks table
CREATE TABLE banks (
    bank_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name   VARCHAR2(100) UNIQUE NOT NULL
);

-- Create the reviews table
CREATE TABLE reviews (
    review_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text      CLOB,
    rating           NUMBER,
    review_date      DATE,
    bank_id          NUMBER,
    source           VARCHAR2(20),
    sentiment_label  VARCHAR2(20),
    sentiment_score  NUMBER,
    FOREIGN KEY (bank_id) REFERENCES banks(bank_id)
);
